/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author visma
 */
public class ProfStudentGradeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfStudentGradeJPanel
     */
    public ProfStudentGradeJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseDescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblManageUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageStudentGrade = new javax.swing.JTable();
        btnAdminView = new javax.swing.JButton();
        btnAdminDelete = new javax.swing.JButton();
        btnAdminUpdate = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();
        lblstatus = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtGrade = new javax.swing.JComboBox<>();

        lblCourseDescription.setBackground(new java.awt.Color(204, 204, 204));
        lblCourseDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseDescription.setText("Course Description:");

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        lblManageUser.setBackground(new java.awt.Color(204, 204, 204));
        lblManageUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblManageUser.setForeground(new java.awt.Color(255, 255, 255));
        lblManageUser.setText("Manage Student Grade");

        tblManageStudentGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "NUID", "UserID", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblManageStudentGrade);

        btnAdminView.setText("View User");
        btnAdminView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminViewActionPerformed(evt);
            }
        });

        btnAdminDelete.setText("Delete User");
        btnAdminDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDeleteActionPerformed(evt);
            }
        });

        btnAdminUpdate.setText("Update User");
        btnAdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUpdateActionPerformed(evt);
            }
        });

        lblStudentName.setBackground(new java.awt.Color(204, 204, 204));
        lblStudentName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student Name");

        lblGrade.setBackground(new java.awt.Color(204, 204, 204));
        lblGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(255, 255, 255));
        lblGrade.setText("Grade:");

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblstatus.setBackground(new java.awt.Color(204, 204, 204));
        lblstatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 255, 255));
        lblstatus.setText("Status:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        txtGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrade)
                            .addComponent(lblstatus)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblManageUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdminUpdate)
                            .addComponent(btnAdminView)
                            .addComponent(btnAdminDelete))))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminDelete, btnAdminUpdate, btnAdminView});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addComponent(btnAdminView)
                .addGap(18, 18, 18)
                .addComponent(btnAdminDelete)
                .addGap(18, 18, 18)
                .addComponent(btnAdminUpdate)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblManageStudentGrade.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblManageStudentGrade.getModel();
        PersonLogin person = history.getPerson().get(selectedRowIndex);
        txtUserName.setText(String.valueOf(person.getUserName()));
        txtUserPassword.setText(decryptPassword(person.getPassword()));
        txtUserID.setText(String.valueOf(person.getUserID()));
        txtNUID.setText(String.valueOf(person.getNuID() == null ? "" : person.getNuID()));

    }//GEN-LAST:event_btnAdminViewActionPerformed

    private void btnAdminDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblManageStudentGrade.getSelectedRow();

        if (selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblManageStudentGrade.getModel();
        PersonLogin person = history.getPerson().get(selectedRowIndex);

        history.deletePerson(person);

        JOptionPane.showMessageDialog(this, "User account deleted.");

        populateTable();
    }//GEN-LAST:event_btnAdminDeleteActionPerformed

    private void btnAdminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblManageStudentGrade.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblManageStudentGrade.getModel();
        PersonLogin person = history.getPerson().get(selectedRowIndex);

        // Retrieve updated values from text fields
        String updatedUserName = txtUserName.getText();
        String updatedNUID = txtNUID.getText();
        String updatedUserID = txtUserID.getText();
        String updatedPassword = txtUserPassword.getText(); // You might want to encrypt it here if needed

        // Update the PersonLogin object
        person.setUserName(updatedUserName);
        person.setNuID(updatedNUID);
        person.setUserID(updatedUserID);
        person.setPassword(updatedPassword);

        // Update the table model to reflect the changes
        model.setValueAt(updatedUserName, selectedRowIndex, 0);
        model.setValueAt(updatedNUID, selectedRowIndex, 1);
        model.setValueAt(updatedUserID, selectedRowIndex, 2);
        model.setValueAt(updatedPassword, selectedRowIndex, 3);

        // No need for history.updateUser() here

        JOptionPane.showMessageDialog(this, "User account updated.");

    }//GEN-LAST:event_btnAdminUpdateActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDelete;
    private javax.swing.JButton btnAdminUpdate;
    private javax.swing.JButton btnAdminView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tblManageStudentGrade;
    private javax.swing.JComboBox<String> txtGrade;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
