/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import login.PersonHistory;
import login.PersonHistoryService;

/**
 *
 * @author visma
 */
public class ProfControlJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfControlJPanel
     */
    
    private PersonHistoryService history;
    
    public ProfControlJPanel() {
        initComponents();
    }

    // Update the constructor to accept a PersonHistoryService parameter
    public ProfControlJPanel(PersonHistoryService history) {
        initComponents();
        this.history = history;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitProfPane = new javax.swing.JSplitPane();
        AdminControl = new javax.swing.JPanel();
        btnProfAddCourse = new javax.swing.JButton();
        btnProfMangSchedule = new javax.swing.JButton();
        btnListUser = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblControl = new javax.swing.JLabel();
        AdminView = new javax.swing.JPanel();

        setBackground(new java.awt.Color(200, 16, 46));

        btnProfAddCourse.setBackground(new java.awt.Color(200, 16, 46));
        btnProfAddCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnProfAddCourse.setText("Add New Course");
        btnProfAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfAddCourseActionPerformed(evt);
            }
        });

        btnProfMangSchedule.setBackground(new java.awt.Color(200, 16, 46));
        btnProfMangSchedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfMangSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnProfMangSchedule.setText("Manage Schedule");
        btnProfMangSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfMangScheduleActionPerformed(evt);
            }
        });

        btnListUser.setBackground(new java.awt.Color(200, 16, 46));
        btnListUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListUser.setForeground(new java.awt.Color(255, 255, 255));
        btnListUser.setText("List User");
        btnListUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUserActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(200, 16, 46));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search User");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblControl.setBackground(new java.awt.Color(200, 16, 46));
        lblControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblControl.setForeground(new java.awt.Color(200, 16, 46));
        lblControl.setText("Professor Control");

        javax.swing.GroupLayout AdminControlLayout = new javax.swing.GroupLayout(AdminControl);
        AdminControl.setLayout(AdminControlLayout);
        AdminControlLayout.setHorizontalGroup(
            AdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnProfAddCourse)
                    .addComponent(btnProfMangSchedule)
                    .addComponent(btnListUser)
                    .addComponent(btnSearch)
                    .addComponent(lblControl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdminControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnListUser, btnProfAddCourse, btnProfMangSchedule, btnSearch});

        AdminControlLayout.setVerticalGroup(
            AdminControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminControlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblControl)
                .addGap(80, 80, 80)
                .addComponent(btnProfAddCourse)
                .addGap(30, 30, 30)
                .addComponent(btnProfMangSchedule)
                .addGap(30, 30, 30)
                .addComponent(btnListUser)
                .addGap(30, 30, 30)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AdminControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnListUser, btnProfAddCourse, btnProfMangSchedule, btnSearch});

        SplitProfPane.setLeftComponent(AdminControl);

        AdminView.setBackground(new java.awt.Color(200, 16, 46));

        javax.swing.GroupLayout AdminViewLayout = new javax.swing.GroupLayout(AdminView);
        AdminView.setLayout(AdminViewLayout);
        AdminViewLayout.setHorizontalGroup(
            AdminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        AdminViewLayout.setVerticalGroup(
            AdminViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        SplitProfPane.setRightComponent(AdminView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitProfPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitProfPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUserActionPerformed
        // TODO add your handling code here:
        ProfViewStudCourseJPanel adminList = new ProfViewStudCourseJPanel();
        SplitProfPane.setRightComponent(adminList);
        
    }//GEN-LAST:event_btnListUserActionPerformed

    private void btnProfMangScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfMangScheduleActionPerformed
        // TODO add your handling code here:
        
        ProfMangScheduleJPanel adminMang = new ProfMangScheduleJPanel();
        SplitProfPane.setRightComponent(adminMang);
    }//GEN-LAST:event_btnProfMangScheduleActionPerformed

    private void btnProfAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfAddCourseActionPerformed
        // TODO add your handling code here:
        
        ProfAddCourseJPanel adminAdd = new ProfAddCourseJPanel();
        SplitProfPane.setRightComponent(adminAdd);
    }//GEN-LAST:event_btnProfAddCourseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        AdminSearchJPanel adminSearch = new AdminSearchJPanel();
        SplitProfPane.setRightComponent(adminSearch);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminControl;
    private javax.swing.JPanel AdminView;
    private javax.swing.JSplitPane SplitProfPane;
    private javax.swing.JButton btnListUser;
    private javax.swing.JButton btnProfAddCourse;
    private javax.swing.JButton btnProfMangSchedule;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblControl;
    // End of variables declaration//GEN-END:variables

}
