/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author visma
 */
public class ProfControlJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfControlJPanel
     */
    public ProfControlJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblProfessorInformation = new javax.swing.JButton();
        BtnStudentLogin = new javax.swing.JButton();
        BtnAdmin1 = new javax.swing.JButton();
        BtnAdmin2 = new javax.swing.JButton();
        BtnStudentLogin2 = new javax.swing.JButton();
        BtnStudentLogin1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        lblProfessorInformation.setBackground(new java.awt.Color(200, 16, 46));
        lblProfessorInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProfessorInformation.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessorInformation.setText("Professor Information");
        lblProfessorInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProfessorInformationActionPerformed(evt);
            }
        });

        BtnStudentLogin.setBackground(new java.awt.Color(200, 16, 46));
        BtnStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStudentLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnStudentLogin.setText("Student Login");
        BtnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStudentLoginActionPerformed(evt);
            }
        });

        BtnAdmin1.setBackground(new java.awt.Color(200, 16, 46));
        BtnAdmin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdmin1.setText("Professor Login");
        BtnAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmin1ActionPerformed(evt);
            }
        });

        BtnAdmin2.setBackground(new java.awt.Color(200, 16, 46));
        BtnAdmin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdmin2.setText("Professor Login");
        BtnAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmin2ActionPerformed(evt);
            }
        });

        BtnStudentLogin2.setBackground(new java.awt.Color(200, 16, 46));
        BtnStudentLogin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStudentLogin2.setForeground(new java.awt.Color(255, 255, 255));
        BtnStudentLogin2.setText("Student Login");
        BtnStudentLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStudentLogin2ActionPerformed(evt);
            }
        });

        BtnStudentLogin1.setBackground(new java.awt.Color(200, 16, 46));
        BtnStudentLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStudentLogin1.setForeground(new java.awt.Color(255, 255, 255));
        BtnStudentLogin1.setText("Student Login");
        BtnStudentLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStudentLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnStudentLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfessorInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnStudentLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblProfessorInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(BtnAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BtnAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(BtnStudentLogin1)
                .addGap(56, 56, 56)
                .addComponent(BtnStudentLogin)
                .addGap(51, 51, 51)
                .addComponent(BtnStudentLogin2)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblProfessorInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProfessorInformationActionPerformed
        // TODO add your handling code here:

        ProfLoginJPanel profLog = new ProfLoginJPanel(SplitMainPane);
        SplitMainPane.setRightComponent(profLog);
    }//GEN-LAST:event_lblProfessorInformationActionPerformed

    private void BtnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStudentLoginActionPerformed
        // TODO add your handling code here:

        StudentLoginJPanel studentLog = new StudentLoginJPanel(SplitMainPane);
        SplitMainPane.setRightComponent(studentLog);
    }//GEN-LAST:event_BtnStudentLoginActionPerformed

    private void BtnAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdmin1ActionPerformed

    private void BtnStudentLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStudentLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnStudentLogin1ActionPerformed

    private void BtnAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdmin2ActionPerformed

    private void BtnStudentLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStudentLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnStudentLogin2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdmin1;
    private javax.swing.JButton BtnAdmin2;
    private javax.swing.JButton BtnStudentLogin;
    private javax.swing.JButton BtnStudentLogin1;
    private javax.swing.JButton BtnStudentLogin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton lblProfessorInformation;
    // End of variables declaration//GEN-END:variables
}
