/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JSplitPane;

/**
 *
 * @author visma
 */
public class ProfLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfLoginJPanel
     */
    private JSplitPane splitMainPane;
    public ProfLoginJPanel(JSplitPane splitMainPane) {
        initComponents();
        this.splitMainPane = splitMainPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogIn = new javax.swing.JButton();
        txtProfPassword = new javax.swing.JPasswordField();
        lblSignIn = new javax.swing.JLabel();
        lblProfUserName = new javax.swing.JLabel();
        txtProfUserName = new javax.swing.JTextField();
        lblProfPassword = new javax.swing.JLabel();

        btnLogIn.setBackground(new java.awt.Color(200, 16, 46));
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        txtProfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfPasswordActionPerformed(evt);
            }
        });

        lblSignIn.setBackground(new java.awt.Color(204, 204, 204));
        lblSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSignIn.setText("Professor Sign In");

        lblProfUserName.setBackground(new java.awt.Color(204, 204, 204));
        lblProfUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProfUserName.setText("User Name:");

        txtProfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfUserNameActionPerformed(evt);
            }
        });

        lblProfPassword.setBackground(new java.awt.Color(204, 204, 204));
        lblProfPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProfPassword.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignIn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfUserName)
                            .addComponent(lblProfPassword))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogIn)
                            .addComponent(txtProfUserName)
                            .addComponent(txtProfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnLogIn)
                .addContainerGap(434, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        String username = txtProfUserName.getText();
        String password = new String(txtProfPassword.getPassword());

        // Hash the user-provided password
        String hashedPassword = hashPassword(password);

        if (username.equals("admin") && history.verifyCredentials(username, hashedPassword)) {
            // Login successful
            AdminJPanel adminPage = new AdminJPanel();
            splitPane.setRightComponent(adminPage);
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid Login!");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtProfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfPasswordActionPerformed

    private void txtProfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel lblProfPassword;
    private javax.swing.JLabel lblProfUserName;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JPasswordField txtProfPassword;
    private javax.swing.JTextField txtProfUserName;
    // End of variables declaration//GEN-END:variables
}
