/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JSplitPane;

/**
 *
 * @author visma
 */
public class StudentLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentLoginJPanel
     */
    
    private JSplitPane splitPane;
    public StudentLoginJPanel() {
        initComponents();
        this.splitPane = splitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogIn = new javax.swing.JButton();
        txtStuPassword = new javax.swing.JPasswordField();
        lblSignIn = new javax.swing.JLabel();
        lblStuUserName = new javax.swing.JLabel();
        txtStuUserName = new javax.swing.JTextField();
        lblStuPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        lblEmailID = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        txtStuID = new javax.swing.JTextField();
        txtNewStuPassword = new javax.swing.JPasswordField();
        lblNewStuPassword = new javax.swing.JLabel();
        btnUserSignUp = new javax.swing.JButton();
        lblSignIn1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSchool = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        lblLevelofEducation = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtLevelofEducation = new javax.swing.JComboBox<>();

        btnLogIn.setBackground(new java.awt.Color(200, 16, 46));
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        txtStuPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuPasswordActionPerformed(evt);
            }
        });

        lblSignIn.setBackground(new java.awt.Color(204, 204, 204));
        lblSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSignIn.setText("Create new Account");

        lblStuUserName.setBackground(new java.awt.Color(204, 204, 204));
        lblStuUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStuUserName.setText("Student ID:");

        txtStuUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuUserNameActionPerformed(evt);
            }
        });

        lblStuPassword.setBackground(new java.awt.Color(204, 204, 204));
        lblStuPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStuPassword.setText("Password:");

        lblName.setBackground(new java.awt.Color(204, 204, 204));
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        lblEmailID.setBackground(new java.awt.Color(204, 204, 204));
        lblEmailID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmailID.setText("Email ID:");

        lblStuID.setBackground(new java.awt.Color(204, 204, 204));
        lblStuID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStuID.setText("Set Student Id:");

        txtStuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStuIDActionPerformed(evt);
            }
        });

        txtNewStuPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewStuPasswordActionPerformed(evt);
            }
        });

        lblNewStuPassword.setBackground(new java.awt.Color(204, 204, 204));
        lblNewStuPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNewStuPassword.setText("Password:");

        btnUserSignUp.setBackground(new java.awt.Color(200, 16, 46));
        btnUserSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnUserSignUp.setText("Sign Up");
        btnUserSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSignUpActionPerformed(evt);
            }
        });

        lblSignIn1.setBackground(new java.awt.Color(204, 204, 204));
        lblSignIn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSignIn1.setText("Existing User");

        jLabel1.setText("student credentials");

        jLabel2.setText("Profile");

        lblSchool.setBackground(new java.awt.Color(204, 204, 204));
        lblSchool.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSchool.setText("School/University:");

        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });

        lblLevelofEducation.setBackground(new java.awt.Color(204, 204, 204));
        lblLevelofEducation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLevelofEducation.setText("Level of Education:");

        lblPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblCountry.setBackground(new java.awt.Color(204, 204, 204));
        lblCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCountry.setText("Country:");

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        txtLevelofEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtLevelofEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelofEducationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lblSignIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(lblSignIn1)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblEmailID)
                                    .addComponent(lblStuID)
                                    .addComponent(lblNewStuPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStuUserName)
                                    .addComponent(lblStuPassword))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogIn)
                            .addComponent(txtStuUserName)
                            .addComponent(txtStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSchool)
                                    .addComponent(lblLevelofEducation)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(lblCountry))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUserSignUp)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txtSchool, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txtLevelofEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStuUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStuUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnLogIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStuID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewStuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLevelofEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLevelofEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnUserSignUp)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        String username = txtStuUserName.getText();
        String password = new String(txtStuPassword.getPassword());

        // Hash the user-provided password
        String hashedPassword = hashPassword(password);

        if (username.equals("admin") && history.verifyCredentials(username, hashedPassword)) {
            // Login successful
            AdminJPanel adminPage = new AdminJPanel();
            splitPane.setRightComponent(adminPage);
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid Login!");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtStuPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuPasswordActionPerformed

    private void txtStuUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuUserNameActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void txtStuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStuIDActionPerformed

    private void txtNewStuPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewStuPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewStuPasswordActionPerformed

    private void btnUserSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSignUpActionPerformed

        String userName = txtName.getText();
        //int nuID = Integer.parseInt(txtNUID.getText());
        String nuID = txtEmailID.getText();
        String userID =txtStuID.getText();
        char[] passwordChars = txtNewStuPassword.getPassword();
        String password = new String(passwordChars);
        PersonLogin newPerson = new PersonLogin(userName, nuID, userID, password);
        history.addPerson(newPerson);

        /*vs.setUserName(userName);
        vs.setNuID(nuID);
        vs.setUserID(userID);
        vs.setPassword(password);*/

        JOptionPane.showMessageDialog(this, "New User Created");

        txtName.setText("");
        txtEmailID.setText("");
        txtStuID.setText("");
        txtNewStuPassword.setText("");

    }//GEN-LAST:event_btnUserSignUpActionPerformed

    private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtLevelofEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelofEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelofEducationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnUserSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblLevelofEducation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewStuPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblSignIn1;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuPassword;
    private javax.swing.JLabel lblStuUserName;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JComboBox<String> txtLevelofEducation;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewStuPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSchool;
    private javax.swing.JTextField txtStuID;
    private javax.swing.JPasswordField txtStuPassword;
    private javax.swing.JTextField txtStuUserName;
    // End of variables declaration//GEN-END:variables
}
