/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author arvin
 */
public class AdminControlJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    public AdminControlJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminSplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        BtnStudentInfo = new javax.swing.JButton();
        BtnProfInfo = new javax.swing.JButton();
        BtnAdminInfo = new javax.swing.JButton();
        WorkAreaPanel = new javax.swing.JPanel();

        BtnStudentInfo.setBackground(new java.awt.Color(200, 16, 46));
        BtnStudentInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStudentInfo.setForeground(new java.awt.Color(255, 255, 255));
        BtnStudentInfo.setText("Student Info");
        BtnStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStudentInfoActionPerformed(evt);
            }
        });

        BtnProfInfo.setBackground(new java.awt.Color(200, 16, 46));
        BtnProfInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnProfInfo.setForeground(new java.awt.Color(255, 255, 255));
        BtnProfInfo.setText("Professor Info");
        BtnProfInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfInfoActionPerformed(evt);
            }
        });

        BtnAdminInfo.setBackground(new java.awt.Color(200, 16, 46));
        BtnAdminInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdminInfo.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdminInfo.setText("Admin Info");
        BtnAdminInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnProfInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAdminInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(BtnStudentInfo)
                .addGap(74, 74, 74)
                .addComponent(BtnProfInfo)
                .addGap(96, 96, 96)
                .addComponent(BtnAdminInfo)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        AdminSplitPane.setLeftComponent(ControlPanel);

        WorkAreaPanel.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
        WorkAreaPanel.setLayout(WorkAreaPanelLayout);
        WorkAreaPanelLayout.setHorizontalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        WorkAreaPanelLayout.setVerticalGroup(
            WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        AdminSplitPane.setRightComponent(WorkAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminSplitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStudentInfoActionPerformed
        // TODO add your handling code here:
        // Remove all components from WorkAreaPanel
        AdminStudentJPanel  adminStuPanel = new AdminStudentJPanel();
        AdminSplitPane.setRightComponent(adminStuPanel);
        
    }//GEN-LAST:event_BtnStudentInfoActionPerformed

    private void BtnAdminInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminInfoActionPerformed
        // TODO add your handling code here:
        AdminInfoJPanel  adminInfoPanel = new  AdminInfoJPanel();
        AdminSplitPane.setRightComponent(adminInfoPanel);
    }//GEN-LAST:event_BtnAdminInfoActionPerformed

    private void BtnProfInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfInfoActionPerformed
        // TODO add your handling code here:
        AdminProfJPanel  adminProfPanel = new AdminProfJPanel();
        AdminSplitPane.setRightComponent(adminProfPanel);
    }//GEN-LAST:event_BtnProfInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane AdminSplitPane;
    private javax.swing.JButton BtnAdminInfo;
    private javax.swing.JButton BtnProfInfo;
    private javax.swing.JButton BtnStudentInfo;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel WorkAreaPanel;
    // End of variables declaration//GEN-END:variables
}
