/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import login.PersonHistory;
import login.PersonHistoryService;
import login.PersonHistoryServiceImpl;
import login.PersonLogin;

/**
 *
 * @author visma
 */
public class StduentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StduentJPanel
     */
    
    
    private PersonHistoryService history;
    
    public StduentJPanel() {
        initComponents();
        this.history = PersonHistoryServiceImpl.getInstance();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentSplitPane = new javax.swing.JSplitPane();
        UserControl = new javax.swing.JPanel();
        btnStudView = new javax.swing.JButton();
        btnStudCrEnrolled = new javax.swing.JButton();
        lblControl = new javax.swing.JLabel();
        btnStudTranscripts = new javax.swing.JButton();
        btnUpdateUser2 = new javax.swing.JButton();
        btnStudExploreCr = new javax.swing.JButton();
        btnUpdateUser4 = new javax.swing.JButton();
        UserWorkArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(247, 247, 247));

        btnStudView.setBackground(new java.awt.Color(200, 16, 46));
        btnStudView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudView.setForeground(new java.awt.Color(255, 255, 255));
        btnStudView.setText("Student Info");
        btnStudView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudViewActionPerformed(evt);
            }
        });

        btnStudCrEnrolled.setBackground(new java.awt.Color(200, 16, 46));
        btnStudCrEnrolled.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudCrEnrolled.setForeground(new java.awt.Color(255, 255, 255));
        btnStudCrEnrolled.setText("Courses Enrolled");
        btnStudCrEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudCrEnrolledActionPerformed(evt);
            }
        });

        lblControl.setBackground(new java.awt.Color(200, 16, 46));
        lblControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblControl.setForeground(new java.awt.Color(200, 16, 46));
        lblControl.setText("Welcome Student");

        btnStudTranscripts.setBackground(new java.awt.Color(200, 16, 46));
        btnStudTranscripts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudTranscripts.setForeground(new java.awt.Color(255, 255, 255));
        btnStudTranscripts.setText("Transcript");
        btnStudTranscripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudTranscriptsActionPerformed(evt);
            }
        });

        btnUpdateUser2.setBackground(new java.awt.Color(200, 16, 46));
        btnUpdateUser2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateUser2.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser2.setText("Extra Key");
        btnUpdateUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUser2ActionPerformed(evt);
            }
        });

        btnStudExploreCr.setBackground(new java.awt.Color(200, 16, 46));
        btnStudExploreCr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudExploreCr.setForeground(new java.awt.Color(255, 255, 255));
        btnStudExploreCr.setText("Explore Courses");
        btnStudExploreCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudExploreCrActionPerformed(evt);
            }
        });

        btnUpdateUser4.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateUser4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateUser4.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser4.setText("Graduate");
        btnUpdateUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUser4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserControlLayout = new javax.swing.GroupLayout(UserControl);
        UserControl.setLayout(UserControlLayout);
        UserControlLayout.setHorizontalGroup(
            UserControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnStudCrEnrolled)
                    .addComponent(btnStudView)
                    .addComponent(lblControl)
                    .addComponent(btnStudTranscripts)
                    .addComponent(btnStudExploreCr)
                    .addComponent(btnUpdateUser2)
                    .addComponent(btnUpdateUser4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UserControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStudCrEnrolled, btnStudExploreCr, btnStudTranscripts, btnStudView, btnUpdateUser2});

        UserControlLayout.setVerticalGroup(
            UserControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserControlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblControl)
                .addGap(59, 59, 59)
                .addComponent(btnStudView)
                .addGap(40, 40, 40)
                .addComponent(btnStudCrEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnStudTranscripts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnStudExploreCr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnUpdateUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnUpdateUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        UserControlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnStudCrEnrolled, btnStudExploreCr, btnStudTranscripts, btnStudView, btnUpdateUser2});

        StudentSplitPane.setLeftComponent(UserControl);

        UserWorkArea.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout UserWorkAreaLayout = new javax.swing.GroupLayout(UserWorkArea);
        UserWorkArea.setLayout(UserWorkAreaLayout);
        UserWorkAreaLayout.setHorizontalGroup(
            UserWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        UserWorkAreaLayout.setVerticalGroup(
            UserWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        StudentSplitPane.setRightComponent(UserWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudViewActionPerformed
        // TODO add your handling code here:
        
        StudentInfoJPanel userView = new StudentInfoJPanel();
        StudentSplitPane.setRightComponent(userView);
        
    }//GEN-LAST:event_btnStudViewActionPerformed

    private void btnStudCrEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudCrEnrolledActionPerformed
        StudentCoursesEnrolledJPanel panelcrenroll = new StudentCoursesEnrolledJPanel();
        StudentSplitPane.setRightComponent(panelcrenroll);
        
        
//        PersonLogin userToDisplay = history.getCurrentUser();
//        
//
//        // Create an instance of StudentUpdateJPanel and pass the user information
//        if (userToDisplay != null) {
//            StudentUpdateJPanel userUpdate = new StudentUpdateJPanel(userToDisplay);
//            UserSplitPane.setRightComponent(userUpdate);
//        } else {
//            // Handle the case when the user is not logged in or userToDisplay is null.
//            // You can show an error message or take appropriate action.
//            // For example, you can display an error dialog.
//            JOptionPane.showMessageDialog(this, "User not found or not logged in. Please log in or try again.");
//        }
//        
    }//GEN-LAST:event_btnStudCrEnrolledActionPerformed

    private void btnStudTranscriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudTranscriptsActionPerformed
        // TODO add your handling code here:
        StudentTranscriptJPanel paneltranscipt = new  StudentTranscriptJPanel();
        StudentSplitPane.setRightComponent(paneltranscipt);
        
    }//GEN-LAST:event_btnStudTranscriptsActionPerformed

    private void btnUpdateUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUser2ActionPerformed

    private void btnStudExploreCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudExploreCrActionPerformed
        // TODO add your handling code here:
        StudentExploreCourseJPanel panel = new StudentExploreCourseJPanel();
        StudentSplitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnStudExploreCrActionPerformed

    private void btnUpdateUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUser4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane StudentSplitPane;
    private javax.swing.JPanel UserControl;
    private javax.swing.JPanel UserWorkArea;
    private javax.swing.JButton btnStudCrEnrolled;
    private javax.swing.JButton btnStudExploreCr;
    private javax.swing.JButton btnStudTranscripts;
    private javax.swing.JButton btnStudView;
    private javax.swing.JButton btnUpdateUser2;
    private javax.swing.JButton btnUpdateUser4;
    private javax.swing.JLabel lblControl;
    // End of variables declaration//GEN-END:variables

    
}
